export const ACTION_TYPES = [
    {value: '', label: 'All Actions'},
    {value: 'user_registered', label: 'Registration'},
    {value: 'user_logged_in', label: 'Login'},
    {value: 'user_logged_out', label: 'Logout'},
    {value: 'user_created', label: 'Create User'},
    {value: 'user_updated', label: 'Update User'},
    {value: 'user_deleted', label: 'Delete User'},
    {value: 'store_created', label: 'Create Store'},
    {value: 'store_updated', label: 'Update Store'},
    {value: 'store_deleted', label: 'Delete Store'},
    {value: 'product_created', label: 'Create Product'},
    {value: 'product_updated', label: 'Update Product'},
    {value: 'product_deleted', label: 'Delete Product'},
    {value: 'order_created', label: 'Create Order'},
    {value: 'order_updated', label: 'Update Order'},
    {value: 'order_deleted', label: 'Delete Order'},
    {value: 'daily_plan_created', label: 'Create Daily Plan'},
    {value: 'daily_plan_updated', label: 'Update Daily Plan'},
    {value: 'daily_plan_deleted', label: 'Delete Daily Plan'},
    {value: 'metrics_saved', label: 'Save Metrics'},
    {value: 'route_calculated', label: 'Calculate Route'},
];