# Generated by Django 5.2.1 on 2025-06-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dailyplan_plan_date_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='plan_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
