# Generated by Django 5.2.1 on 2025-06-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dailyplan_plan_date_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyplanstore',
            unique_together={('daily_plan', 'store'), ('daily_plan', 'visit_order')},
        ),
    ]
